### ISSUE TITLE
MXID var

### ISSUE THREAD

**Issue by array-in-a-matrix** [jjj333-p/matrix-word-counter#2]
https://github.com/jjj333-p/matrix-word-counter/blob/45e92effd008096315b6847b52e1c71e598c0404/index.js#L30

Why create a new var for mxid? You can access it from `Client.userId`.

**Comment by jjj333-p** [comment]
because dumb. i do the same thing in spam police :facepalm: 

spam police will be fully rewrote

**Comment by jjj333-p** [comment]
so turns out i did this for a reason, dumbass client makes a fetch for every time you run that. anyways it did  highlight a thing i was supposed to uncomment
